//CRIANDO LIVROS DA TABELA LIVROS
import Knex from 'knex';

export async function seed(knex: Knex) {
  await knex('book').insert([
    {
      name: 'It a coisa',
      author: 'Stephen King',
      year: 1986,
      genre: 'Terror, Suspense',
      publisher: 'Viking Press',
      page: 1138,
      status: 'Alugado',
    },
    {
      name: 'The amityville horror',
      author: 'Jay Anson',
      year: 1977,
      genre: 'Terror',
      publisher: 'Prentice Hall',
      page: 240,
      status: 'Disponível',
    },
    {
      name: 'Garota exemplar',
      author: 'Gillian Flynn',
      year: 2012,
      genre: 'Romance, Mistério, Ficção, Suspense',
      publisher: 'Intrinseca',
      page: 448,
      status: 'Disponível',
    },
    {
      name: 'Como eu era antes de você',
      author: 'Jojo Moyes',
      year: 2012,
      genre: 'Romance, Ficção',
      publisher: 'Penguin Books',
      page: 480,
      status: 'Alugado',
    },
    {
      name: 'Crepúsculo',
      author: 'Stephenie Meyer',
      year: 2005,
      genre: 'Romance, Terror',
      publisher: 'Little, Brown and Company',
      page: 498,
      status: 'Disponível',
    },
    {
      name: 'The outsider',
      author: 'Stephen King',
      year: 2018,
      genre: 'Romance, Terror, Suspense, Mistério',
      publisher: 'Charles Scribners Sons',
      page: 560,
      status: 'Alugado',
    },
    {
      name: 'A assombração da casa da colina',
      author: 'Shirley Jackson',
      year: 1959,
      genre: 'Romance, Terror, Ficção gótica',
      publisher: 'Viking Press',
      page: 246,
      status: 'Alugado',
    },
    {
      name: 'The chronicles of narnia',
      author: 'Clive Staples Lewis',
      year: 1956,
      genre: 'Literatura fantástica',
      publisher: 'M. Fontes',
      page: 751,
      status: 'Disponível',
    },
    {
      name: 'A hora do pesadelo',
      author: 'Carlos Primati, Thommy Hutson',
      year: 2017,
      genre: 'Terror, Suspense',
      publisher: 'Darkside Books',
      page: 520,
      status: 'Alugado',
    },
    {
      name: 'O que aconteceu com annie',
      author: 'C.J. Tudor',
      year: 2019,
      genre: 'Suspense',
      publisher: 'Intrinseca',
      page: 288,
      status: 'Disponível',
    },
  ]);
}
