//CRIANDO LIVROS DA TABELA LIVROS
import Knex from 'knex';

export async function seed(knex: Knex) {
  await knex('livros').insert([
    {
      nome: 'It a coisa',
      autor: 'Stephen King',
      ano: 1986,
      genero: 'Terror, Suspense',
      editora: 'Viking Press',
      paginas: 1138,
      status: 'Alugado',
    },
    {
      nome: 'The Amityville Horror',
      autor: 'Jay Anson',
      ano: 1977,
      genero: 'Terror',
      editora: 'Prentice Hall',
      paginas: 240,
      status: 'Disponível',
    },
    {
      nome: 'Garota Exemplar',
      autor: 'Gillian Flynn',
      ano: 2012,
      genero: 'Romance, Mistério, Ficção, Suspense',
      editora: 'Intrinseca',
      paginas: 448,
      status: 'Disponível',
    },
    {
      nome: 'Como eu era antes de você',
      autor: 'Jojo Moyes',
      ano: 2012,
      genero: 'Romance, Ficção',
      editora: 'Penguin Books',
      paginas: 480,
      status: 'Alugado',
    },
    {
      nome: 'Crepúsculo',
      autor: 'Stephenie Meyer',
      ano: 2005,
      genero: 'Romance, Terror',
      editora: 'Little, Brown and Company',
      paginas: 498,
      status: 'Disponível',
    },
    {
      nome: 'The Outsider',
      autor: 'Stephen King',
      ano: 2018,
      genero: 'Romance, Terror, Suspense, Mistério',
      editora: 'Charles Scribners Sons',
      paginas: 560,
      status: 'Alugado',
    },
    {
      nome: 'A Assombração da Casa da Colina',
      autor: 'Shirley Jackson',
      ano: 1959,
      genero: 'Romance, Terror, Ficção gótica',
      editora: 'Viking Press',
      paginas: 246,
      status: 'Alugado',
    },
    {
      nome: 'The Chronicles of Narnia',
      autor: 'Clive Staples Lewis',
      ano: 1956,
      genero: 'Literatura fantástica',
      editora: 'M. Fontes',
      paginas: 751,
      status: 'Disponível',
    },
    {
      nome: 'A Hora Do Pesadelo',
      autor: 'Carlos Primati, Thommy Hutson',
      ano: 2017,
      genero: 'Terror, Suspense',
      editora: 'Darkside Books',
      paginas: 520,
      status: 'Alugado',
    },
    {
      nome: 'O Que Aconteceu Com Annie',
      autor: 'C.J. Tudor',
      ano: 2019,
      genero: 'Suspense',
      editora: 'Intrinseca',
      paginas: 288,
      status: 'Disponível',
    },
  ]);
}
